In [2]:
# List
a = [1, 2, 3]
print(a)

[1, 2, 3]


In [20]:
# Numpy
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [13]:
# Get dimension
print(a, f'Dimension: {a.ndim}')
print(b, f'Dimension: {b.ndim}')

[1 2 3] Dimension: 1
[[1 2 3]
 [4 5 6]] Dimension: 2


In [15]:
# Get shapes
print(a, f'Shapes: {a.shape}')
print(b, f'Shapes: {b.shape}')

[1 2 3] Shapes: (3,)
[[1 2 3]
 [4 5 6]] Shapes: (2, 3)


In [21]:
# Get type
print(a.dtype)
a = np.array(a, dtype='int8')
a.dtype

int32


dtype('int8')

In [22]:
# Get size in bytes
print(a.itemsize)
print(b.itemsize) 

1
4


In [25]:
# Get total size: size*itemsize
b.nbytes

24

## Initializing diff types of arrays

In [30]:
a = np.arange(1,15).reshape(2, 7)
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [36]:
# All zeroes
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
# All ones
b = np.ones((3,2), dtype='int')
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [51]:
# All identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# Any other no
np.full((2,2), 88)

array([[88, 88],
       [88, 88]])

In [49]:
# Random array
np.random.randint(low=0, high=10, size=(4, 3))

array([[8, 9, 7],
       [6, 6, 2],
       [7, 2, 6],
       [2, 9, 1]])

In [50]:
# Random float array
np.round(np.random.uniform(low=0, high=10, size=(4, 3)),2)

array([[6.78, 7.69, 1.88],
       [3.79, 1.24, 9.04],
       [8.66, 6.83, 3.84],
       [7.35, 9.62, 2.42]])

In [53]:
# Repeating array
a = np.array([[1, 2, 3]])
np.repeat(a, 3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [60]:
a = np.ones((5,5))
a[1:4,1:4], a[2,2] = 0, 9
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Copying cells

In [62]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 8
b
a

array([1, 2, 3])

In [70]:
#  Multiplying
a = np.ones((2,3))
b = np.random.randint(2, 8, (3,2))
np.matmul(a, b)

array([[16., 15.],
       [16., 15.]])

In [73]:
# Finding determinant
a = np.identity(3)
np.linalg.det(a)

1.0

In [74]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

In [75]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
np.min(stats)

1

In [77]:
np.max(stats, axis=1)

array([3, 6])

In [78]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [79]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Taking input from the file

In [85]:
data = np.genfromtxt('data.txt', delimiter=',')
data = data.astype('int')
data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean Masking and Advanced Indexing

In [87]:
data[data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [91]:
# Accesing index as list
a = np.arange(1,11)
a[[1, 4, -1]]

array([ 2,  5, 10])

In [93]:
np.any(data>50, axis=1)

array([ True,  True,  True])

In [98]:
a = np.arange(1,31).reshape((6,5))
a[2:4,:2]

array([[11, 12],
       [16, 17]])

In [102]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [103]:
a[[0,-2,-1],-2:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])